# Generated by Django 4.1.4 on 2023-01-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ToList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(default=False, help_text="Статус выполнения"),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Задача")),
                (
                    "slug",
                    models.SlugField(blank=True, unique=True, verbose_name="URL Post"),
                ),
                ("date_complite", models.DateTimeField()),
                ("date_create", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
