# Generated by Django 4.1.4 on 2023-01-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mylist", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tolist",
            name="date_complite",
            field=models.DateTimeField(blank=True),
        ),
    ]
